Azure-Samples/azure-search-openai-javascript

- .devcontainer/devcontainer.json
- .github/workflows/azure-dev.yaml
- infra/main.bicep
- infra/main.parameters.json
> ci: add continuous deployment (#3)

- .devcontainer/devcontainer.json
- README.md
- azure.yaml
- infra/core/host/container-app.bicep
- infra/main.bicep
- infra/main.parameters.json
- packages/search/src/app.ts
- packages/search/src/plugins/config.ts
- packages/search/src/plugins/cors.ts
~~I need to deploy it first to test it~~
> feat(search): configure CORS

- packages/chat-component/src/core/http/index.ts
- packages/search/src/lib/approaches/approach-base.ts
- packages/search/src/lib/approaches/approach.ts
- packages/search/src/lib/approaches/ask-read-retrieve-read.ts
- packages/search/src/lib/approaches/ask-retrieve-then-read.ts
- packages/search/src/lib/approaches/chat-read-retrieve-read.ts
- packages/search/src/plugins/schemas.ts
- packages/search/src/routes/root.ts
- packages/search/test.http
- packages/webapp/src/api/api.ts
- packages/webapp/src/api/models.ts
- packages/webapp/src/components/AnalysisPanel/AnalysisPanel.tsx
- packages/webapp/src/components/Answer/Answer.tsx
- packages/webapp/src/pages/chat/Chat.tsx
- packages/webapp/src/pages/oneshot/OneShot.tsx
Currently missing 2 things:
- update for chat-component response
- update the input message history format
These 2 missing changes will be done in a separate PR as it involves big changes on the frontend
> feat: conform to chat protocol (#67)

- packages/chat-component/src/core/http/index.ts
- packages/search/src/lib/approaches/approach.ts
- packages/search/src/lib/approaches/chat-read-retrieve-read.ts
- packages/search/src/lib/message.ts
- packages/search/src/plugins/schemas.ts
- packages/search/src/routes/root.ts
- packages/search/test.http
Previous PR was missing request conformance
> feat(search): conforms api requests to chat protocol (#67)

- .devcontainer/devcontainer.json
- package-lock.json
- package.json
- packages/eslint-config/index.js
- tests/load/README.md
- tests/load/chat.js
- tests/load/config.js
- tests/load/index.js
- tests/load/mainpage.js
Uses [k6](https://k6.io/) to perform load testing for the start page as well as the /chat endpoint 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:  Tests
```
Set the following environment variables to point to the deployment.
```
export WEBAPP_URI=<webapp_uri>
export SEARCH_API_URI=<search_api_uri>
```
Once set, you can now run load tests using the following command:
```
npm run test:load
```
> test: add load tests 

- packages/chat-component/src/main.ts
- tests/e2e/hars/default-ask-response.har
- tests/e2e/webapp.spec.ts
Add a E2E test for the "Ask a question" interaction.  
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Test
```
npm run test:playwright
> test: add playwright test for ask interaction

- README.md
- infra/main.bicep
- infra/main.parameters.json
The model won't deploy with gpt4, but I don't understand why:
```
SpecialFeatureOrQuotaIdRequired: The current subscription does not have feature required by this model 'Format: OpenAI, Name: gpt-4, Version: 0613' and SKU 'Standard'.
```
Tried in both my subscription (which has GPT4 enabled) and the CDA sub, same error. 
Model is available in the default region eastus2 (https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#model-summary-table-and-region-availability) so it's not that.
> feat: make it easier to use gpt4

- README.md
Node.js 20 is not supported but the current LTS is 18. So we're replacing the requirement.
Closes #116
> fix: update required node version with LTS

- package-lock.json
- packages/indexer/package.json
- packages/search/package.json
Fixes the @azure/identity issue reported here: https://github.com/Azure/azure-sdk-for-js/issues/27704
Since `azd` does a `npm install` instead of `npm ci`, the version gets automatically updated to the broken 3.4.0, breaking managed identity on deployed services.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
> fix: update and fix @azure/identity to v4.0.0

- .devcontainer/devcontainer.json
javascript-node:18-bullseye should fix this issue: https://github.com/Azure/azure-dev/issues/2942
> Use javascript-node:18-bullseye for devcontainer

- packages/chat-component/src/main.ts
Fix for #132 where voice input overlaps with reset input. Only shows voice input if there is no reset button. 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
> fix: only show voice input if reset input is not set

- azure.yaml
- scripts/index-data.ps1
- ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
```
```
- ...
> fix: fix powershell issues

- packages/chat-component/src/config/global-config.js
- packages/chat-component/src/core/http/index.ts
- packages/chat-component/src/core/parser/index.ts
- packages/chat-component/src/main.ts
- packages/chat-component/src/style.ts
- packages/chat-component/src/types.d.ts
- packages/chat-component/src/utils/index.ts
- packages/search/README.md
- packages/search/src/routes/root.ts
- tests/e2e/hars/error-chat-response-stream.har
- tests/e2e/webapp.spec.ts
Handle the content filtered errors from Open AI better. For reference: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter
Changes include: 
- Handling bad request errors separately from internal server errors
- Handle content filtering in the middle of streamed output. 
- Fix bug where error message is not sticky to the user input but is only shown once. 
- Fix bug where loading indicator does not show up after an error
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[X] Feature
```
- Get the code
```
cd [repo-name]
git …
```
> fix: Handle errors from input filtering better

- README.md
Propose additional security measures in the readme
> docs: update README.md with additional security measures

- README.md
- packages/indexer/bin/index-files.js
Fixes path issues on Windows.
A warning due to using experimental feature in Node 18 will be displayed at runtime though, but does not impact the result.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
> fix(indexer): incorrect path on Windows (#141)

- packages/chat-component/src/components/chat-action-button.ts
- packages/chat-component/src/components/chat-component.ts
- packages/chat-component/src/components/chat-thread-component.ts
- packages/chat-component/src/components/citation-list.ts
- packages/chat-component/src/components/loading-indicator.ts
- packages/chat-component/src/components/tab-component.ts
- packages/chat-component/src/components/teaser-list-component.ts
- packages/chat-component/src/components/voice-input-button.ts
- packages/chat-component/src/styles/chat-action-button.ts
- packages/chat-component/src/styles/chat-component.ts
- packages/chat-component/src/styles/chat-thread-component.ts
- packages/chat-component/src/styles/citation-list.ts
- packages/chat-component/src/styles/loading-indicator.ts
- packages/chat-component/src/styles/tab-component.ts
- packages/chat-component/src/styles/teaser-list-component.ts
- packages/chat-component/src/styles/voice-input-button.ts
- tests/e2e/webapp.spec.ts
- Cleans up the lit element styles 
- Shows which citation is being previewed across all the citation references
- Cleans up button styles to be less pronounced
- Clean up tabs and teaser list component to be sharable for more than default prompts
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
- Get the code
```
cd [repo-name]
npm install
```
```
npm run test
npm run test:playwright
```
> chore: clean up styles for the lit elements

- packages/indexer/src/lib/document-processor.ts
- packages/indexer/src/lib/indexer.ts
Fixes last comment from @shibbas on PR #149 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
> refactor(indexer): extract handlers

- .devcontainer/devcontainer.json
- package-lock.json
- packages/chat-component/package.json
- packages/webapp/package.json
Fixes #176 and vite vulnerability. 
vite  4.0.0 - 4.5.1
Severity: high
Vite XSS vulnerability in `server.transformIndexHtml` via URL payload - https://github.com/advisories/GHSA-92r3-m2mg-pj97
Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem - https://github.com/advisories/GHSA-c24v-8rfc-w8vw
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
```
```
- ...
> Fix: package vulnerability and indexer deployment

- .github/workflows/azure-dev-validation.yaml
- .github/workflows/azure-dev.yaml
- .github/workflows/build-test.yaml
- .github/workflows/playwright.yml
- .github/workflows/stale-bot.yml
Update actions to remove CI warnings
```
[ ] Yes
[x] No
```
> ci: update actions

- .devcontainer/devcontainer.json
Opening a local version of the repo causes issues with using the docker daemon. This version of docker does not cause conflicts. 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
```
Deployed.
```
- ...
> chore: update docker dependencies

- .devcontainer/devcontainer.json
- packages/chat-component/src/components/chat-component.ts
- packages/webapp/src/pages/oneshot/OneShot.tsx
```
- [x ] bug report -> please search issues before submitting
```
> azd auth login
> azd up
> go to static web app
> select any of the default search questions and click the search buttoon
> open the though process
> verify there is text like "[DynamicTool]" in there
> Open the Developer Settings in upper right corner
> Notice the "Retrieve-Then-Read" is selected
The ask-read-retrieve-read is the approach that uses the Dynamic Tool. 
You can try changing the approach in the Developer Settings, but it does not seem to work.
Also the OneShot.tsx file does have the rrr hard-coded.
> Change the approach being used when the Developer Setting is changed
> Pass the selected approach to the chat component and to the api call

- packages/indexer/src/lib/document-processor.ts
This change will better support CJK documents when splitting text
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
```
```
- ...
> Add ideographic and fullwidth punctuation to splitter

- infra/core/security/managed-identity.bicep
- infra/main.bicep
- packages/indexer/src/lib/document-processor.ts
New AZD templates were missing user assigned identities
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
> fix: deployment issues (fixes #161)

- packages/search/src/lib/approaches/chat-read-retrieve-read.ts
-Added safe navigation to an object that might be undefined on an empty conversation. -Fixes #201
- Prevents an error in new projects where empty choices are returned because of the lack of context history.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
- Get the code
```
cd [repo-name]
npm install
```
```
Spin up a new project
Validate that the console displays no errors
```
- A new conversation without prior context should have no error when retrieving the …
> Fix error with undefined choices in new conversations

- infra/core/ai/cognitiveservices.bicep
- infra/main.bicep
Disable Azure OpenAI local auth to comply with new enforced security policies.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: infra
```
> chore: disable local auth for azure openai

- azure.yaml
- ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
```
```
- ...
> docs: update azure.yaml
