Azure-Samples/azure-search-openai-javascript

package-lock.json, packages/chat-component/package.json, packages/chat-component/src/main.ts
=> feat: enable xss sanitization

packages/chat-component/src/config/global-config.js, packages/chat-component/src/core/http/index.ts, packages/chat-component/src/main.ts
Enable requests to /ask endpoint
=> feat: add ask support

README.md
This will allow this sample to be referenced in https://learn.microsoft.com/en-us/samples/browse/
=> docs: add frontmatter for learn indexing

packages/chat-component/src/main.ts
=> feat: add delete chat button

packages/webapp/src/pages/chat/Chat.tsx
@Pamelafox mentioned customers asked about retrieval mode. It would be nice to have the answer in a tooltip closer to the user's needs than a doc. 
- ...
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
```
- Get the code
```
cd [repo-name]
npm install
npm start
```
Open developer settings. 
```
```
Hover over any of the settings. 
- ...
=> Tooltip for Developer settings

README.md
Local connection also requires docker to build. Update Readme.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
=> local connection also requires docker to build

packages/webapp/src/i18n/tooltips.ts, packages/webapp/src/pages/chat/Chat.tsx, packages/webapp/src/pages/oneshot/OneShot.tsx
Default style makes it hard to differentiate from the background so set the tooltip to light grey. No ability to control the text color that I could find. 
Also separated out the strings for the tooltips so Chris and Arun (or anyone) could change the text without worrying about the surrounding code. 
- ...
```
[ ] Yes
[ X] No
```
```
[X ] Bugfix
[ X] Feature
```
- Get the code
```
cd [repo-name]
npm install
npm start
```
Hover over item in Developer settings. 
```
```
Verify that the following are …
=> Tooltips fix for style and const

README.md
readme update for authentication compliance information.
=> docs: update readme with auth info

infra/main.bicep, infra/main.parameters.json
I almost got the CD working by creating a SP manually with the rights to assign the roles needed.
This is the only piece missing: during a CD, we do not need to assign user roles as they are only needed when the user runs the app locally, and these roles are tied to the user.
=> chore(infra): detect CD

packages/chat-component/src/utils/index.ts
Looks like the next question parsing broke ask when there is no match. This fixes that. 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
```
npm run test:playwright
```
=> fix: ask next question parsing to handle no match for next questions

packages/chat-component/src/main.ts
- ...
```
[ ] Yes
[ x] No
```
```
[ x] Bugfix
[ ] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
Submit a question from the default questions. Wait for the frontend to render the questions.
```
```
Follow up questions have the question mark.
- ...
=> fix: add question mark to follow up questions

packages/webapp/src/pages/layout/Layout.tsx
Edit incorrect link and update description from web app to JavaScript repo
- ...
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Other: update links
```
=> fix: fix link back from webapp

README.md
=> fix: update env var variable

README.md
This Pull Request is related with **#107** which we should include the `--purge` parameter to the `azd down` command
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
```
```
- ...
=> fix: include a parameter for 'azd down --purge' command

README.md
=> fix: update services in metadata for tamplate display

azure.yaml
Fix #120 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> fix(infra): fix windows issue on predeploy (#120, #117)

README.md
- ...
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
Service rebranding
=> docs: replace cognitive search mentions with Azure AI Search

README.md
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> docs: add video overview link

README.md
Adds link to https://github.com/microsoft/generative-ai-for-beginners in the readme
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> docs: add link to gen ai for beginners

README.md
Update protocol link to the new public repo.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> docs: update protocol and link (fixes #150)

packages/indexer/src/lib/document-processor.ts
Tested on a very small doc, works fine
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> fix: text splitter with tiny documents (fixes #193)

packages/indexer/src/plugins/openai.ts, packages/search/src/plugins/openai.ts
Old API version will be deprecated starting July, 1st.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
=> chore: update openai api version

README.md, docs/README.md
Updates link to AI Chat Protocol
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
- Click link
=> Update protocol link

README.md, SECURITY.md
Fixes issues reported by #210
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> docs: azd template compliance (closes #210)

infra/main.parameters.json
- ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
- Get the code
```
cd [repo-name]
npm install
```
```
```
- ...
=> fix: update model

.github/workflows/build-test.yaml, README.md, docs/low-cost.md, infra/main.bicep, package-lock.json, packages/indexer/package.json, packages/indexer/src/lib/indexer.ts, packages/indexer/src/plugins/config.ts, packages/indexer/src/routes/indexes/index.ts, packages/indexer/test/helper.ts, packages/search/package.json, packages/search/src/lib/approaches/approach-base.ts, packages/search/src/plugins/config.ts, packages/search/src/routes/root.ts, packages/search/test.http, packages/search/test/helper.ts
- upgrade to latest AI search SDK
- add doc for low cost deployment
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
[x] Refactoring (no functional changes, no api changes)
```
=> refactor: upgrade AI search SDK and add doc for low cost deployment
